import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import '../styles/globals.css';
// filepath: z:\Drive\Astra data\Brella Slider\Brella bot\my-voiceflow-app\app\layout.tsx
// ...existing code...
import '../styles/globals.css';
// ...existing code...


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Astra Chatbot",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}



